# Generated by Django 2.2.7 on 2020-04-25 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0033_delete_application'),
        ('application', '0007_remove_application_jobpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='jobpost',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='jobboard.PostJob'),
        ),
    ]
