# Generated by Django 2.2.7 on 2020-04-25 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20200426_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='application',
            name='jobpost',
        ),
    ]
